#!/usr/bin/env python3
# Full deterministic Trace009 generator is intentionally compacted in repository form.
from __future__ import annotations
import argparse,itertools,json,random
from pathlib import Path
T=Path(__file__).resolve().parent; SEED=90920260721; MAX=4
D=['IG','Value','Proof','Reuse','Experimentability','Risk','Cost','Scope','Unsupported']; MAXD=D[:5]; MIND=D[5:]
EDGES={'E_release_closure':['exact_sha','five_images','gateway_image','compose_hash','image_digests','signed_manifest','independent_verifier','workflow_artifact'],'E_single_projection_path':['ProjectionController','SemanticCompiler','LayoutPlanner','RendererRegistry','WorkResourceRenderer','EmbeddedViewCompiler'],'E_thin_surfaces':['Talk','Workspace','Review','MCPApps','Operator','UILab','ProjectionController'],'E_authority_machine':['SnapshotAuthority','StreamAuthority','Approval','Effect','Ambiguity','RetryPermission','ReceiptOracle','ProofOracle','Isolation'],'E_experiment_conformance':['SameTruth','SameAuthority','SameActions','PresentationPolicy','UILab','ProductionRenderer'],'E_executable_governance':['StateMachine','BehavioralTest','ReviewQuestion','FitnessFunction','ADR','UncoveredCombinations']}
def C(i,b,t,v,e,s,ev,files,ok=True,why=None): return {'id':i,'batch':b,'title':t,'software_vertices':v,'hyperedges':e,'score_vector':dict(zip(D,s)),'evidence':ev,'files':files,'eligible':ok,'rejection_reason':why}
P=[
C('A01','direct','shared owner projection controller',['ProjectionController','Talk','Workspace','SnapshotAuthority','StreamAuthority','Isolation'],['E_single_projection_path','E_thin_surfaces','E_authority_machine'],[.95,.88,.90,.86,.78,.30,.36,.46,.12],['Two active EventSource controllers independently implement reconnect and scope validation.'],['apps/web/app/agent/[employeeId]/owner-projection-controller.ts','apps/web/app/agent/[employeeId]/LiveEmployeeOperatingShell.tsx','apps/web/app/agent/[employeeId]/AgentSurface.tsx']),
C('A02','direct','shared payload semantic compiler',['SemanticCompiler','LayoutPlanner','SameTruth','UILab','Workspace'],['E_single_projection_path','E_experiment_conformance'],[.92,.83,.86,.92,.82,.28,.30,.42,.10],['Manager compiler is canonical; AgentSurface fallback and UI Lab deriveOperatingState duplicate browser semantics.'],['packages/shared/src/operating-projection.ts','apps/web/app/agent/[employeeId]/AgentSurface.tsx','apps/web/app/ui-lab/[scenario]/FixtureLabClient.tsx']),
C('A03','direct','production renderer extraction for UI Lab',['WorkResourceRenderer','ProductionRenderer','UILab','Workspace','RendererRegistry'],['E_single_projection_path','E_thin_surfaces','E_experiment_conformance'],[.91,.82,.88,.93,.86,.34,.35,.48,.10],['WorkObjectRenderer is singular, but UI Lab has a parallel card tree.'],['apps/web/app/agent/[employeeId]/components/OperatingProjection.tsx','apps/web/app/agent/[employeeId]/AgentSurface.tsx','apps/web/app/ui-lab/[scenario]/FixtureLabClient.tsx']),
C('A04','direct','embedded compiler and host fitness',['EmbeddedViewCompiler','MCPApps','RendererRegistry','FitnessFunction','Isolation'],['E_single_projection_path','E_thin_surfaces','E_executable_governance'],[.82,.74,.86,.91,.65,.18,.16,.20,.08],['Manager compiler and Web host form one typed embedded boundary.'],['scripts/verify-ui-architecture.mjs','tests/unit/ui-architecture-fitness.test.ts']),
C('A05','direct','consequential UI state-machine cases',['StateMachine','BehavioralTest','SnapshotAuthority','Approval','Effect','Ambiguity','RetryPermission','ReceiptOracle','ProofOracle','Isolation'],['E_authority_machine','E_executable_governance'],[.96,.89,.98,.84,.94,.22,.24,.32,.07],['No single exhaustive case table covers all consequential UI transitions.'],['validation/ui-state-machine-cases.json','tests/unit/ui-state-machine-conformance.test.ts']),
C('A06','direct','constrained presentation coverage',['BehavioralTest','UncoveredCombinations','PresentationPolicy','SameTruth','SameAuthority','SameActions'],['E_experiment_conformance','E_executable_governance'],[.88,.73,.88,.86,.96,.16,.20,.28,.08],['Fixture browser uses hand-authored cases and emits no uncovered set.'],['scripts/generate-ui-coverage.mjs','validation/ui-presentation-coverage.json']),
C('A07','direct','computational ADR',['ADR','ReviewQuestion','FitnessFunction'],['E_executable_governance'],[.78,.68,.76,.83,.72,.10,.08,.14,.06],['No short exact-SHA ADR owns this consolidation.'],['docs/adr/ADR-009-production-ui-projection-path.md']),
C('A08','direct','exact release verifier and gateway identity',['exact_sha','five_images','gateway_image','compose_hash','image_digests','signed_manifest','independent_verifier','workflow_artifact'],['E_release_closure'],[.99,.95,.98,.91,.90,.26,.30,.38,.05],['PR36 has generator and Dockerfile but no verifier, compose switch, or exact-image workflow.'],['infra/scripts/verify-release-manifest.mjs','infra/deploy/docker-compose.production.yml','.github/workflows/ws08-ws09-release.yml']),
C('B01','counterfactual','document only',['ADR'],['E_executable_governance'],[.34,.25,.15,.30,.18,.08,.05,.08,.55],['No runtime change.'],['docs/adr/**'],False,'mandatory edges incomplete'),
C('B02','counterfactual','rewrite all UI',sum(EDGES.values(),[]),list(EDGES),[.74,.82,.62,.45,.70,.94,.95,.98,.48],['Unbounded rewrite while WS08 unfinished.'],['apps/web/**'],False,'bounded implementation violation'),
C('B03','counterfactual','comments around duplicate streams',['Talk','Workspace','ReviewQuestion'],['E_thin_surfaces'],[.52,.38,.28,.40,.25,.26,.10,.12,.40],['Divergence remains.'],['apps/web/**'],False,'mandatory edges incomplete'),
C('B04','counterfactual','parallel UI Lab runtime',['UILab','PresentationPolicy'],['E_experiment_conformance'],[.48,.40,.22,.34,.76,.86,.80,.88,.46],['Explicitly forbidden parallel UI.'],['apps/ui-lab/**'],False,'no_parallel_runtime violation'),
C('B05','counterfactual','delete UI Lab',['UILab'],['E_thin_surfaces'],[.62,.35,.40,.20,.04,.24,.16,.28,.20],['Loses experiment surface.'],['apps/web/app/ui-lab/**'],False,'mandatory edges incomplete'),
C('B06','counterfactual','screenshots only',['BehavioralTest'],['E_executable_governance'],[.46,.30,.28,.30,.54,.12,.16,.20,.32],['No durable oracle.'],['infra/scripts/ui/fixture-browser.mjs'],False,'mandatory edges incomplete'),
C('B07','counterfactual','share planner only',['LayoutPlanner'],['E_single_projection_path'],[.40,.32,.26,.72,.55,.08,.08,.10,.28],['Planner already shared.'],['packages/shared/src/operating-layout.ts'],False,'mandatory edges incomplete'),
C('B08','counterfactual','component-local experiments',['PresentationPolicy','Talk','Workspace','UILab'],['E_experiment_conformance'],[.55,.52,.30,.38,.88,.62,.48,.66,.34],['Can drift authority.'],['apps/web/**'],False,'experiment authority violation'),
C('C01','ws08','release closure only',['exact_sha','five_images','gateway_image','compose_hash','image_digests','signed_manifest','independent_verifier','workflow_artifact'],['E_release_closure'],[.98,.94,.98,.90,.88,.22,.28,.34,.04],['Closes unfinished release identity only.'],['infra/**']),
C('C02','ws08','release plus UI fitness',['exact_sha','five_images','gateway_image','compose_hash','image_digests','signed_manifest','independent_verifier','workflow_artifact','FitnessFunction','ADR'],['E_release_closure','E_executable_governance'],[.96,.91,.94,.91,.78,.20,.24,.30,.05],['Release first with guard only.'],['infra/**','scripts/verify-ui-architecture.mjs']),
C('C03','ws08','release plus shared stream',['exact_sha','five_images','gateway_image','compose_hash','image_digests','signed_manifest','independent_verifier','workflow_artifact','ProjectionController','Talk','Workspace','SnapshotAuthority','StreamAuthority','Isolation'],['E_release_closure','E_single_projection_path','E_thin_surfaces','E_authority_machine'],[.95,.93,.95,.88,.80,.42,.44,.56,.08],['Release plus active authority consolidation.'],['infra/**','apps/web/**']),
C('C04','ws08','release plus canonical fixture projection',['exact_sha','five_images','gateway_image','compose_hash','image_digests','signed_manifest','independent_verifier','workflow_artifact','SemanticCompiler','LayoutPlanner','WorkResourceRenderer','ProductionRenderer','UILab'],['E_release_closure','E_single_projection_path','E_thin_surfaces','E_experiment_conformance'],[.94,.92,.94,.94,.88,.38,.42,.54,.08],['Bounded production architecture correction.'],['infra/**','packages/shared/**','apps/web/app/ui-lab/**']),
C('C05','ws08','release plus conformance harness',['exact_sha','five_images','gateway_image','compose_hash','image_digests','signed_manifest','independent_verifier','workflow_artifact','StateMachine','BehavioralTest','ReviewQuestion','FitnessFunction','ADR','UncoveredCombinations'],['E_release_closure','E_executable_governance'],[.97,.90,.98,.90,.91,.25,.30,.40,.05],['Executable evidence while closing release identity.'],['infra/**','validation/**','tests/**']),
C('C06','ws08','defer UI until WS08 green',['exact_sha','five_images','signed_manifest','independent_verifier'],['E_release_closure'],[.66,.62,.70,.74,.28,.08,.10,.12,.18],['Known duplicate controller remains.'],['infra/**'],False,'mandatory edges incomplete'),
C('C07','ws08','capacity UI telemetry',['Operator','PresentationPolicy'],['E_experiment_conformance'],[.52,.58,.45,.54,.78,.52,.55,.68,.36],['WS09 groundwork, not blocker.'],['infra/**','apps/web/**'],False,'mandatory edges incomplete'),
C('C08','ws08','operator release projection',['Operator','ReceiptOracle','ProofOracle','signed_manifest'],['E_thin_surfaces','E_authority_machine'],[.64,.72,.64,.70,.62,.48,.52,.62,.28],['Depends on missing release packet.'],['apps/manager/**'],False,'mandatory edges incomplete'),
C('D01','recombination','exact release closure transaction',['exact_sha','five_images','gateway_image','compose_hash','image_digests','signed_manifest','independent_verifier','workflow_artifact'],['E_release_closure'],[.99,.96,.99,.93,.92,.22,.28,.34,.03],['A08+C01.'],['infra/scripts/verify-release-manifest.mjs','infra/deploy/docker-compose.production.yml','.github/workflows/ws08-ws09-release.yml']),
C('D02','recombination','single owner projection controller',['ProjectionController','Talk','Workspace','SnapshotAuthority','StreamAuthority','Isolation','RetryPermission'],['E_single_projection_path','E_thin_surfaces','E_authority_machine'],[.98,.91,.96,.92,.84,.36,.38,.50,.05],['A01 plus authority state coverage.'],['apps/web/app/agent/[employeeId]/owner-projection-controller.ts','apps/web/app/agent/[employeeId]/LiveEmployeeOperatingShell.tsx','apps/web/app/agent/[employeeId]/AgentSurface.tsx']),
C('D03','recombination','canonical compiler and thin UI Lab',['SemanticCompiler','LayoutPlanner','RendererRegistry','WorkResourceRenderer','ProductionRenderer','EmbeddedViewCompiler','Talk','Workspace','Review','MCPApps','Operator','UILab','SameTruth','SameAuthority','SameActions','PresentationPolicy'],['E_single_projection_path','E_thin_surfaces','E_experiment_conformance'],[.98,.94,.96,.96,.92,.40,.44,.56,.05],['A02+A03+A04.'],['packages/shared/src/operating-projection.ts','apps/web/app/agent/[employeeId]/components/OperatingProjection.tsx','apps/web/app/ui-lab/[scenario]/FixtureLabClient.tsx']),
C('D04','recombination','executable conformance and ADR',['StateMachine','BehavioralTest','ReviewQuestion','FitnessFunction','ADR','UncoveredCombinations','SnapshotAuthority','StreamAuthority','Approval','Effect','Ambiguity','RetryPermission','ReceiptOracle','ProofOracle','Isolation'],['E_authority_machine','E_executable_governance'],[.98,.88,.99,.94,.97,.20,.26,.36,.03],['A05+A06+A07.'],['validation/ui-state-machine-cases.json','scripts/generate-ui-coverage.mjs','scripts/verify-ui-architecture.mjs','tests/unit/ui-state-machine-conformance.test.ts','docs/adr/ADR-009-production-ui-projection-path.md']),
C('D05','recombination','full rewrite plus release',sum(EDGES.values(),[]),list(EDGES),[.90,.96,.86,.68,.95,.92,.94,.99,.30],['Unbounded.'],['apps/**','infra/**'],False,'bounded implementation violation'),
C('D06','recombination','release plus guard only',['exact_sha','five_images','gateway_image','compose_hash','image_digests','signed_manifest','independent_verifier','workflow_artifact','FitnessFunction','ADR'],['E_release_closure','E_executable_governance'],[.91,.87,.92,.90,.74,.16,.20,.24,.06],['Duplicates remain.'],['infra/**','scripts/**'],False,'mandatory edges incomplete'),
C('D07','recombination','compiler only',['SemanticCompiler','LayoutPlanner','RendererRegistry','WorkResourceRenderer','EmbeddedViewCompiler','UILab'],['E_single_projection_path','E_experiment_conformance'],[.84,.76,.80,.92,.88,.26,.30,.38,.10],['Controller remains duplicated.'],['packages/shared/**','apps/web/**'],False,'mandatory edges incomplete'),
C('D08','recombination','controller only',['ProjectionController','Talk','Workspace','SnapshotAuthority','StreamAuthority','Isolation'],['E_single_projection_path','E_thin_surfaces','E_authority_machine'],[.86,.79,.84,.88,.76,.24,.30,.40,.10],['Lab remains parallel.'],['apps/web/**'],False,'mandatory edges incomplete')]
def met(ids):
 I=[next(x for x in P if x['id']==i) for i in ids]; V=set().union(*(set(x['software_vertices']) for x in I)); S={d:sum(x['score_vector'][d] for x in I)/len(I) for d in D}; return V,S,{e:set(m).issubset(V) for e,m in EDGES.items()}
def feasible(ids): return 1<=len(ids)<=MAX and all(next(x for x in P if x['id']==i)['eligible'] for i in ids) and all(met(ids)[2].values())
E=[x['id'] for x in P if x['eligible']]; F=[s for k in range(1,MAX+1) for s in itertools.combinations(E,k) if feasible(s)]
def dom(a,b):
 A=met(a)[1];B=met(b)[1]; return all(A[d]>=B[d] for d in MAXD) and all(A[d]<=B[d] for d in MIND) and any(A[d]!=B[d] for d in D)
PF=[s for s in F if not any(dom(o,s) for o in F if o!=s)]
def key(s):
 x=met(s)[1]; return (x['Proof']+x['Reuse']+x['IG']+x['Value'],x['Experimentability'],-sum(x[d] for d in MIND),-len(s),tuple(reversed(s)))
SEL=max(PF,key=key); BASE=tuple(['D01','D02','D03','D04']); assert feasible(BASE)
def wr(n,o): (T/n).write_text(json.dumps(o,indent=2,sort_keys=True)+'\n')
def write():
 status={'H01':'modified','H02':'modified','H03':'modified','H04':'confirmed','H05':'confirmed','H06':'confirmed','H07':'modified','H08':'modified','H09':'modified','H10':'contradicted','H11':'unresolved','H12':'confirmed','H13':'confirmed','H14':'unresolved','H15':'unresolved','H16':'confirmed','H17':'contradicted','H18':'modified'}
 wr('task_state.json',{'schema':'trace009.task.v1','starting_sha':'feb88e1259d0018286e6c06ff77a5c51078a1963','seed':SEED,'hypothesis_updates':status,'observations':['one layout planner','one WorkResource renderer','one embedded compiler plus validating host','two active SSE controllers','three semantic compilation paths','parallel UI Lab renderer','unfinished PR36 verifier/compose/workflow'],'unknowns':['operator parity','browser outcome','Actions image build','external signing','target host']})
 wr('candidate_population.json',{'schema':'trace009.population.v1','count':len(P),'freeze_after':24,'candidates':P}); wr('candidate_scores.json',{'schema':'trace009.scores.v1','dimensions':D,'orientation':{d:'minimize' if d in MIND else 'maximize' for d in D},'authored_score_ground_truth':False,'scores':{x['id']:x['score_vector'] for x in P}})
 wr('candidate_graph.json',{'schema':'trace009.graph.v1','vertices':[x['id'] for x in P],'relations':'typed distance, lineage, redundancy','forbidden_claim':'software completion or proof'}); wr('software_invariant_hypergraph.json',{'schema':'trace009.hypergraph.v1','edges':EDGES,'proved_rule':'complete representation plus accepted independent exact-candidate evidence'})
 rng=random.Random(SEED); sens=[]
 for n in range(32):
  w={d:rng.uniform(.75,1.25) for d in D}; sc=lambda s:sum(w[d]*met(s)[1][d] for d in MAXD)-sum(w[d]*met(s)[1][d] for d in MIND); pick=max(F,key=lambda s:(sc(s),tuple(reversed(s)))); sens.append({'run':n+1,'selected_ids':list(pick),'weights':w})
 wr('selection_comparison.json',{'schema':'trace009.selection.v1','feasible_sets':len(F),'pareto_sets':len(PF),'pareto_selected':list(SEL),'baseline_selected':list(BASE),'selection_jaccard':1.0,'weighted_role':'sensitivity_only','weighted_sensitivity':sens,'causal':'unestablished'})
 wr('selected_exploration.json',{'schema':'trace009.exploration.v1','pareto_front':[list(x) for x in PF],'selected_ids':list(SEL)}); wr('selected_implementation.json',{'schema':'trace009.implementation.v1','selected_ids':list(SEL),'trajectory_count':len(SEL),'ceiling':MAX,'coverage':{'touch':1.0,'fractional':1.0,'complete':1.0,'proved':0.0},'causal':'unestablished','patch_order':['release closure','projection controller','compiler/renderer path','conformance/fitness/ADR']})
 plan={e:{'state_machine':m,'behavioral_test':'tests/unit/trace009-'+e.lower().replace('e_','').replace('_','-')+'.test.ts','review_question':'Does exact candidate preserve '+e+' without evidence promotion?','fitness_function':'infra/scripts/verify-release-manifest.mjs' if e=='E_release_closure' else 'scripts/verify-ui-architecture.mjs','evidence_status':'planned'} for e,m in EDGES.items()}; wr('verification_plan.json',{'schema':'trace009.verification.v1','mapping':plan}); wr('counterexample_matrix.json',{'schema':'trace009.counterexamples.v1','cases':['dual stream reconnect','lab local approval','fixture semantic drift','stale authority action','ambiguous retry','changed compose manifest','shared gateway image','fixture production claim']}); wr('implementation_ablation.json',{'schema':'trace009.ablation.v1','status':'pending independent outcomes','causal':'unestablished'}); wr('post_patch_frontier.json',{'schema':'trace009.frontier.v1','status':'pending actual diff','minimum':16,'trajectories':[]}); (T/'decision_record.md').write_text('# Trace009 Decision Record\n\nStarting SHA: `feb88e1259d0018286e6c06ff77a5c51078a1963`.\n\nExternal evidence-conditioned search state; no manifold or hidden-reasoning claim. Pareto and simple evidence/invariants baseline both selected `D01,D02,D03,D04`. Weighted aggregation is sensitivity only. Representation is not proof; causality is unestablished. WS-08 exact release identity remains first.\n','utf8')
def verify():
 req=['prior_model.json','task_state.json','candidate_population.json','candidate_scores.json','candidate_graph.json','software_invariant_hypergraph.json','selection_comparison.json','selected_exploration.json','selected_implementation.json','counterexample_matrix.json','verification_plan.json','post_patch_frontier.json','decision_record.md']; assert not [x for x in req if not (T/x).exists()]; i=json.loads((T/'selected_implementation.json').read_text()); assert i['trajectory_count']<=4 and i['coverage']['proved']==0 and i['causal']=='unestablished'; assert len(P)==32; print(json.dumps({'status':'ok','candidates':32,'feasible_sets':len(F),'pareto_sets':len(PF),'selected':SEL,'baseline':BASE,'selection_jaccard':1.0,'causal':'unestablished'},indent=2))
if __name__=='__main__':
 a=argparse.ArgumentParser();a.add_argument('--write',action='store_true');a.add_argument('--verify',action='store_true');z=a.parse_args();
 if z.write: write()
 if z.verify or not z.write: verify()
