#!/usr/bin/env node
/**
 * Phase 1 acceptance report. Runs each run{1..8} verifier, aggregates pass/fail/
 * not-run, prints a summary, and writes a structured report to
 * infra/acceptance/reports/phase01-<ts>.json (+ .md) suitable to paste into an
 * implementation record.
 *
 * HONESTY: a run is `pass` only when its verifier found real proof ids in the live
 * environment. With no creds every run is `not-run` — never a fabricated pass.
 * Exit code: 1 if any run FAILED, else 0 (all not-run is not a failure).
 *
 *   npm run acceptance:report
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { STATUS } from "./_env.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const MODULES = [
  "run1-db-rls", "run2-provision", "run3-artifact", "run4-gmail",
  "run5-stripe", "run6-reminder", "run7-repair-eventbus", "run8-security",
];

const results = [];
for (const m of MODULES) {
  try {
    const mod = await import(`./${m}.mjs`); // importing does NOT auto-run (isMain guard)
    results.push(await mod.verify());
  } catch (e) {
    results.push({ id: m, key: m, label: m, status: STATUS.FAIL, proofs: {}, missing: [], notes: [String(e?.message ?? e)] });
  }
}
results.sort((a, b) => Number(a.id) - Number(b.id));

const counts = { pass: 0, fail: 0, "not-run": 0 };
for (const r of results) counts[r.status] = (counts[r.status] ?? 0) + 1;

console.log("AMTECH Phase 1 — provider/runtime acceptance report\n");
for (const r of results) {
  const icon = r.status === STATUS.PASS ? "✓" : r.status === STATUS.FAIL ? "✗" : "•";
  console.log(`${icon} Run ${r.id} — ${r.label}: ${r.status.toUpperCase()}`);
  for (const [k, v] of Object.entries(r.proofs ?? {})) console.log(`    ${k}: ${v}`);
  if (r.missing?.length) console.log(`    missing env: ${r.missing.join(", ")}`);
  for (const n of r.notes ?? []) console.log(`    note: ${n}`);
}
console.log(`\nSummary: ${counts.pass} pass · ${counts.fail} fail · ${counts["not-run"]} not-run (of ${results.length})`);

const accepted = counts.pass === results.length;
console.log(
  accepted
    ? "\nPhase 1 PROVIDER/RUNTIME ACCEPTED — all runs passed with real proof ids."
    : "\nPhase 1 NOT yet accepted — fill env, run the runbooks, and capture real proof. (not-run = nothing to verify yet.)",
);

const ts = new Date().toISOString().replace(/[:.]/g, "-");
const dir = join(here, "..", "..", "acceptance", "reports");
mkdirSync(dir, { recursive: true });
const payload = {
  phase: 1,
  generated_at: new Date().toISOString(),
  accepted,
  counts,
  realness: "Statuses reflect live DB/endpoint proof only. not-run = required env absent. No injected provider results.",
  runs: results,
};
const jsonPath = join(dir, `phase01-${ts}.json`);
writeFileSync(jsonPath, JSON.stringify(payload, null, 2));

const md = [
  `# Phase 1 acceptance report — ${payload.generated_at}`,
  "",
  `Accepted: **${accepted ? "YES" : "NO"}** — ${counts.pass} pass · ${counts.fail} fail · ${counts["not-run"]} not-run`,
  "",
  "| Run | Area | Status | Proof / missing |",
  "|---|---|---|---|",
  ...results.map((r) => {
    const detail = r.status === STATUS.NOT_RUN
      ? `missing: ${(r.missing ?? []).join(", ")}`
      : Object.entries(r.proofs ?? {}).map(([k, v]) => `${k}=${v}`).join("; ") || "(no proofs)";
    return `| ${r.id} | ${r.label} | ${r.status} | ${detail.replace(/\|/g, "\\|")} |`;
  }),
  "",
  "_Generated by `npm run acceptance:report`. not-run = required env absent; no provider results were injected._",
].join("\n");
const mdPath = join(dir, `phase01-${ts}.md`);
writeFileSync(mdPath, md);

console.log(`\nWrote ${jsonPath}`);
console.log(`Wrote ${mdPath}`);
process.exit(counts.fail > 0 ? 1 : 0);
