/* AUTO-GENERATED by scripts/ui-variant.mjs. Do not edit by hand. */
import { lazy } from "react";
import type { UiVariantManifest } from "@amtech/shared";

export const UI_VARIANT_MANIFESTS = [
  {
    schema: "amtech.ui-variant.v1",
    id: "standard-reference",
    name: "Standard capability reference",
    description: "A neutral reference proving the complete employee experience contract without copying production layout.",
    contract_version: 1,
    entry: "index.tsx",
    conformance: "web_client_capable",
    status: "candidate",
    adapters: ["owner_web", "public_form", "boundless_website"],
    capabilities: ["conversation", "work", "attention", "approvals", "connections", "evidence", "outputs"],
    intentionally_omitted: [],
    features: [],
    packages: [],
  },
  {
    schema: "amtech.ui-variant.v1",
    id: "radical-canvas",
    name: "Radical spatial canvas",
    description: "An intentionally unfamiliar spatial operating canvas proving visual freedom beyond the normal Web client.",
    contract_version: 1,
    entry: "index.tsx",
    conformance: "web_client_capable",
    status: "experiment",
    adapters: ["owner_web", "boundless_website"],
    capabilities: ["conversation", "work", "attention", "approvals", "connections", "evidence", "outputs"],
    intentionally_omitted: [],
    features: ["canvas"],
    packages: [],
  },
] as const satisfies readonly UiVariantManifest[];

export type UiVariantRegistryId = typeof UI_VARIANT_MANIFESTS[number]["id"];

export const UI_VARIANT_LOADERS = {
  "standard-reference": lazy(() => import("./standard-reference/index")),
  "radical-canvas": lazy(() => import("./radical-canvas/index")),
} as const;

export function uiVariantManifest(id: string | null | undefined): UiVariantManifest | null {
  return UI_VARIANT_MANIFESTS.find((item) => item.id === id) ?? null;
}
