#!/usr/bin/env node
import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, extname, posix, relative, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import process from "node:process";

const ROOT = process.cwd();
const TRACE = "mvp-build/decision/trace010";
const TASK = JSON.parse(execFileSync("git", ["show", `HEAD:${TRACE}/task_state.json`], { encoding: "utf8" }));
const BASE_SHA = valueAfter("--base-sha") ?? TASK.starting_sha;
const OUTPUT = resolve(ROOT, valueAfter("--output") ?? `${TRACE}/generated`);
const MAX_BUFFER = 1024 * 1024 * 256;

function valueAfter(flag) {
  const index = process.argv.indexOf(flag);
  return index >= 0 ? process.argv[index + 1] : undefined;
}
function sha256(buffer) {
  return createHash("sha256").update(buffer).digest("hex");
}
function git(args, encoding = null) {
  return execFileSync("git", args, { cwd: ROOT, encoding, maxBuffer: MAX_BUFFER });
}
function parseTree(ref) {
  const raw = git(["ls-tree", "-r", "-z", "--full-tree", ref]);
  return raw.toString("binary").split("\0").filter(Boolean).map((entry) => {
    const tab = entry.indexOf("\t");
    const [mode, type, object] = entry.slice(0, tab).split(" ");
    return { mode, type, object, path: entry.slice(tab + 1) };
  });
}
function blob(object) {
  return git(["cat-file", "blob", object]);
}
function isBinary(buffer) {
  const sample = buffer.subarray(0, Math.min(buffer.length, 8192));
  return sample.includes(0);
}
function language(path) {
  const ext = extname(path).toLowerCase();
  return ({
    ".ts": "typescript", ".tsx": "typescript-react", ".js": "javascript", ".mjs": "javascript-module",
    ".cjs": "javascript-commonjs", ".json": "json", ".md": "markdown", ".mdx": "mdx", ".py": "python",
    ".sql": "sql", ".sh": "shell", ".yml": "yaml", ".yaml": "yaml", ".toml": "toml", ".css": "css",
    ".scss": "scss", ".html": "html", ".xml": "xml", ".txt": "text", ".csv": "csv", ".svg": "svg"
  })[ext] ?? (posix.basename(path).toLowerCase().includes("dockerfile") ? "dockerfile" : ext.slice(1) || "unknown");
}
function generatedReasons(path, text, binary) {
  const reasons = [];
  if (/(^|\/)(dist|build|coverage|\.next|generated)(\/|$)/i.test(path)) reasons.push("generated_path_segment");
  if (/(^|\/)(package-lock\.json|npm-shrinkwrap\.json|pnpm-lock\.yaml|yarn\.lock)$/i.test(path)) reasons.push("lockfile");
  if (/validation\/(?:.*coverage|.*snapshot|.*manifest|.*report)/i.test(path)) reasons.push("retained_validation_output");
  if (!binary && /(?:@generated|generated file|do not edit|autogenerated)/i.test(text.slice(0, 4096))) reasons.push("generated_header");
  return reasons;
}
function evidenceClass(path) {
  if (path.startsWith(".github/workflows/")) return "workflow";
  if (/\/migrations\//.test(path)) return "durable_state_source";
  if (/\/(tests?|__tests__)\//.test(path) || /\.test\.[^.]+$/.test(path)) return "executable_test";
  if (/\/decision\//.test(path)) return "decision_record";
  if (/\/validation\//.test(path)) return "retained_evidence";
  if (/\/docs\//.test(path) || /\.mdx?$/.test(path)) return "documentation";
  if (/\/(scripts|infra)\//.test(path)) return "executable_script_or_config";
  if (/\/(apps|packages)\//.test(path)) return "executable_source";
  return "repository_configuration";
}
function authoritySignals(path, text) {
  const signals = [];
  const name = posix.basename(path);
  if (/^STANDARD.*\.md$/.test(name)) signals.push("normative_requirement_candidate");
  if (name === "AGENTS.md" || name === "CLAUDE.md") signals.push("agent_interface_candidate");
  if (name === "CODEGRAPH.md") signals.push("topology_authority_candidate");
  if (/production-readiness|active program|sole active|canonical|normative|authority/i.test(text.slice(0, 20000))) signals.push("authority_language");
  if (/historical|superseded|archive|provenance only/i.test(text.slice(0, 20000))) signals.push("historical_language");
  return signals;
}
function sideEffectSignals(text) {
  const patterns = {
    filesystem_write: /\b(writeFile|appendFile|rename|unlink|rmSync|mkdir|createWriteStream)\b/,
    process_execution: /\b(execFile|execSync|spawn|child_process)\b/,
    network_io: /\b(fetch\s*\(|axios\.|https?\.request|WebSocket|EventSource)\b/,
    database_write: /\b(INSERT|UPDATE|DELETE|UPSERT|transaction\s*\(|\.insert\(|\.update\(|\.delete\()\b/i,
    environment_dependency: /\b(process\.env|Deno\.env|getenv\s*\()\b/,
    container_or_host_control: /\b(docker|compose|systemctl|caddy|iptables|ufw)\b/i,
    workflow_control: /\b(actions\/checkout|workflow_dispatch|pull_request|push:)\b/
  };
  return Object.entries(patterns).filter(([, pattern]) => pattern.test(text)).map(([name]) => name);
}
function machineReadability(path, text, binary) {
  if (binary) return { level: "opaque_binary", parse: "not_attempted" };
  const ext = extname(path).toLowerCase();
  if (ext === ".json") {
    try { JSON.parse(text); return { level: "structured", parse: "valid_json" }; }
    catch { return { level: "structured_invalid", parse: "invalid_json" }; }
  }
  if ([".yml", ".yaml", ".toml", ".xml", ".csv"].includes(ext)) return { level: "structured_unvalidated", parse: ext.slice(1) };
  if ([".ts", ".tsx", ".js", ".mjs", ".cjs", ".py", ".sql", ".sh"].includes(ext)) return { level: "executable_text", parse: language(path) };
  if ([".md", ".mdx", ".txt"].includes(ext)) return { level: "human_text", parse: language(path) };
  return { level: "plain_or_unknown", parse: language(path) };
}
function normalizeText(text) {
  return text.replace(/\r\n/g, "\n").replace(/\s+/g, " ").trim().toLowerCase();
}
function extractPathTokens(path, text) {
  const tokens = new Set();
  const add = (value) => {
    if (!value || /^(?:https?:|mailto:|data:|#)/.test(value)) return;
    const clean = value.split(/[?#]/)[0].replace(/^['"`(<\[]+|['"`)>\],;:]+$/g, "");
    if (clean.includes("/")) tokens.add(clean);
  };
  for (const match of text.matchAll(/(?:from\s+|import\s*\(|require\s*\(|new\s+URL\s*\()\s*["'`]([^"'`]+)["'`]/g)) add(match[1]);
  for (const match of text.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)) add(match[1]);
  for (const match of text.matchAll(/(?:^|[\s"'`(])((?:\.\.?\/|mvp-build\/|\.github\/)?[A-Za-z0-9_@.-]+(?:\/[A-Za-z0-9_@.{}*\[\]-]+)+)/gm)) add(match[1]);
  return [...tokens].map((token) => ({ source_path: path, token }));
}
function resolveToken(sourcePath, token, known) {
  const candidates = [];
  const normalized = token.replace(/^\.\//, "");
  if (known.has(normalized)) candidates.push(normalized);
  if (known.has(`mvp-build/${normalized}`)) candidates.push(`mvp-build/${normalized}`);
  const fromDir = posix.normalize(posix.join(posix.dirname(sourcePath), token));
  if (known.has(fromDir)) candidates.push(fromDir);
  const extensions = ["", ".ts", ".tsx", ".js", ".mjs", ".cjs", ".json", ".md", "/index.ts", "/index.tsx", "/index.js"];
  for (const base of [normalized, `mvp-build/${normalized}`, fromDir]) {
    for (const suffix of extensions) if (known.has(`${base}${suffix}`)) candidates.push(`${base}${suffix}`);
  }
  return [...new Set(candidates)];
}

const entireTree = parseTree(BASE_SHA).filter((entry) => entry.type === "blob");
const allKnownPaths = new Set(entireTree.map((entry) => entry.path));
const mvpEntries = entireTree.filter((entry) => entry.path.startsWith("mvp-build/"));
const allTextRecords = [];
const rawMvp = [];

for (const entry of entireTree) {
  const content = blob(entry.object);
  const binary = isBinary(content);
  const text = binary ? "" : content.toString("utf8");
  if (!binary) allTextRecords.push({ path: entry.path, text });
  if (!entry.path.startsWith("mvp-build/")) continue;
  const generated = generatedReasons(entry.path, text, binary);
  rawMvp.push({
    path: entry.path,
    git_mode: entry.mode,
    git_blob_sha: entry.object,
    sha256: sha256(content),
    bytes: content.length,
    lines: binary ? null : (text.length === 0 ? 0 : text.split(/\r?\n/).length),
    estimated_tokens: binary ? null : Math.ceil(text.length / 4),
    language: language(entry.path),
    binary,
    generated: generated.length > 0,
    generated_reasons: generated,
    evidence_class: evidenceClass(entry.path),
    authority_signals: authoritySignals(entry.path, text),
    side_effect_signals: binary ? [] : sideEffectSignals(text),
    machine_readability: machineReadability(entry.path, text, binary),
    normalized_text_sha256: binary ? null : sha256(Buffer.from(normalizeText(text))),
    path_tokens: binary ? [] : extractPathTokens(entry.path, text)
  });
}

const inbound = new Map(rawMvp.map((record) => [record.path, []]));
const outbound = new Map(rawMvp.map((record) => [record.path, []]));
const unresolved = [];
for (const record of allTextRecords) {
  for (const tokenRecord of extractPathTokens(record.path, record.text)) {
    const targets = resolveToken(record.path, tokenRecord.token, allKnownPaths).filter((target) => target.startsWith("mvp-build/"));
    if (targets.length === 0) {
      if (/^(?:\.\.?\/|mvp-build\/)/.test(tokenRecord.token)) unresolved.push(tokenRecord);
      continue;
    }
    for (const target of targets) {
      inbound.get(target)?.push({ source: record.path, token: tokenRecord.token });
      if (outbound.has(record.path)) outbound.get(record.path).push({ target, token: tokenRecord.token });
    }
  }
}

const exactGroups = new Map();
const normalizedGroups = new Map();
for (const record of rawMvp.filter((item) => !item.binary)) {
  if (!exactGroups.has(record.sha256)) exactGroups.set(record.sha256, []);
  exactGroups.get(record.sha256).push(record.path);
  if (!normalizedGroups.has(record.normalized_text_sha256)) normalizedGroups.set(record.normalized_text_sha256, []);
  normalizedGroups.get(record.normalized_text_sha256).push(record.path);
}
const duplicates = {
  exact: [...exactGroups.entries()].filter(([, paths]) => paths.length > 1).map(([hash, paths]) => ({ hash, paths: paths.sort() })),
  normalized: [...normalizedGroups.entries()].filter(([, paths]) => paths.length > 1).map(([hash, paths]) => ({ hash, paths: paths.sort() }))
};

const vectors = rawMvp.map((record) => {
  const incoming = inbound.get(record.path) ?? [];
  const outgoing = outbound.get(record.path) ?? [];
  const authority = record.authority_signals.length ? record.authority_signals : ["no_explicit_authority_signal"];
  const runtimeReach = record.evidence_class === "executable_source" || record.evidence_class === "executable_script_or_config"
    ? (incoming.length > 0 ? "referenced_executable" : "unresolved_executable_reach")
    : incoming.length > 0 ? "referenced_nonruntime" : "no_observed_reference";
  const experimentability = record.evidence_class === "executable_test" || /(?:verify|generate|test|experiment|trace)/i.test(record.path)
    ? "directly_executable_or_generated"
    : incoming.some((item) => /(?:test|workflow|scripts|decision)/i.test(item.source)) ? "indirectly_exercised" : "unknown";
  const uncertainty = [];
  if (record.binary) uncertainty.push("binary_content_not_semantically_parsed");
  if (runtimeReach.startsWith("unresolved")) uncertainty.push("runtime_reach_not_proved_by_static_reference");
  if (incoming.length === 0) uncertainty.push("no_observed_inbound_reference");
  if (record.generated && record.generated_reasons.includes("retained_validation_output")) uncertainty.push("generated_but_retained_evidence_policy_requires_review");
  return {
    path: record.path,
    evidence: {
      git_blob_sha: record.git_blob_sha,
      sha256: record.sha256,
      inbound_references: incoming,
      outbound_references: outgoing
    },
    x_f: {
      authority,
      runtimeReach,
      sideEffects: record.side_effect_signals.length ? record.side_effect_signals : ["none_observed_by_static_patterns"],
      evidenceClass: record.evidence_class,
      duplication: {
        exact_group_size: exactGroups.get(record.sha256)?.length ?? 1,
        normalized_group_size: record.normalized_text_sha256 ? normalizedGroups.get(record.normalized_text_sha256)?.length ?? 1 : null
      },
      tokenCost: record.estimated_tokens,
      machineReadability: record.machine_readability,
      coupling: { inbound_count: incoming.length, outbound_count: outgoing.length },
      uncertainty: uncertainty.length ? uncertainty : ["none_observed_by_declared_rules"],
      experimentability
    },
    generated: record.generated,
    generated_reasons: record.generated_reasons,
    bytes: record.bytes,
    lines: record.lines,
    language: record.language
  };
});

const authorityCandidates = vectors.filter((item) => item.x_f.authority[0] !== "no_explicit_authority_signal");
const pressure = [...vectors].sort((a, b) => {
  const ap = a.x_f.coupling.inbound_count + a.x_f.coupling.outbound_count + a.x_f.sideEffects.length + a.x_f.authority.length;
  const bp = b.x_f.coupling.inbound_count + b.x_f.coupling.outbound_count + b.x_f.sideEffects.length + b.x_f.authority.length;
  return bp - ap || a.path.localeCompare(b.path);
}).slice(0, 100).map((item) => item.path);

const extractionRules = {
  authority: "path-owned authority filenames plus explicit authority/canonical/active/historical language; no semantic truth inferred",
  runtimeReach: "static inbound references and executable-path classification; absence remains unresolved rather than dead",
  sideEffects: "declared source-pattern families for filesystem, process, network, database, environment, host and workflow control",
  evidenceClass: "path-based source/test/workflow/decision/evidence/documentation taxonomy",
  duplication: "exact SHA-256 and whitespace-normalized lowercase SHA-256 groups",
  tokenCost: "ceil(UTF-8 character count / 4); binary is null",
  machineReadability: "extension class plus strict JSON parse where applicable",
  coupling: "resolved path/import/link references across the complete starting-SHA tree",
  uncertainty: "explicit static-analysis gaps; Unknown is never zero",
  experimentability: "direct executable/test/generator naming or observed reference from test/workflow/script/decision paths"
};

const summary = {
  schema: "trace010.inventory-summary.v1",
  starting_sha: BASE_SHA,
  tracked_repository_blobs: entireTree.length,
  tracked_mvp_build_blobs: rawMvp.length,
  generated_mvp_build_blobs: rawMvp.filter((item) => item.generated).length,
  non_generated_mvp_build_blobs: rawMvp.filter((item) => !item.generated).length,
  binary_mvp_build_blobs: rawMvp.filter((item) => item.binary).length,
  authority_candidate_count: authorityCandidates.length,
  unresolved_path_token_count: unresolved.length,
  exact_duplicate_group_count: duplicates.exact.length,
  normalized_duplicate_group_count: duplicates.normalized.length,
  high_pressure_paths: pressure,
  extraction_rules: extractionRules
};

await mkdir(OUTPUT, { recursive: true });
await writeFile(resolve(OUTPUT, "before_tree.txt"), rawMvp.map((item) => item.path).sort().join("\n") + "\n");
await writeFile(resolve(OUTPUT, "inventory_summary.json"), JSON.stringify(summary, null, 2) + "\n");
await writeFile(resolve(OUTPUT, "file_inventory.json"), JSON.stringify({ schema: "trace010.file-inventory.v1", starting_sha: BASE_SHA, extraction_rules: extractionRules, files: vectors.sort((a, b) => a.path.localeCompare(b.path)) }, null, 2) + "\n");
await writeFile(resolve(OUTPUT, "path_reference_index.json"), JSON.stringify({ schema: "trace010.path-references.v1", starting_sha: BASE_SHA, inbound: Object.fromEntries([...inbound.entries()].sort()), outbound: Object.fromEntries([...outbound.entries()].sort()), unresolved }, null, 2) + "\n");
await writeFile(resolve(OUTPUT, "duplicate_groups.json"), JSON.stringify({ schema: "trace010.duplicates.v1", starting_sha: BASE_SHA, ...duplicates }, null, 2) + "\n");
await writeFile(resolve(OUTPUT, "authority_candidates.json"), JSON.stringify({ schema: "trace010.authority-candidates.v1", starting_sha: BASE_SHA, candidates: authorityCandidates }, null, 2) + "\n");

console.log(JSON.stringify(summary, null, 2));
