import type { ResourcePayload, WorkEventRow } from "./surface-types";

const now = "2026-07-09T11:30:00Z";

function workEvent(
  id: string,
  move: "notify" | "question" | "review",
  title: string,
  summary: string,
  deliverable: NonNullable<WorkEventRow["work_event_descriptor"]>["deliverable"],
  suggested_next_action?: string,
): WorkEventRow {
  return {
    id,
    event_type: `ui_fixture.${move}`,
    status: move === "review" ? "needs_review" : "delivered",
    created_at: now,
    work_event_descriptor: {
      account_id: "acct_ui_fixture",
      employee_id: "emp_ui_fixture",
      source_event_id: id,
      move,
      title,
      summary,
      deliverable,
      suggested_next_action,
      proof: { fixture: "ui_only", source: "local_fixture" },
    },
  };
}

export function fixtureResourcePayload(employeeId: string): ResourcePayload {
  const payload: ResourcePayload = {
    account_id: "acct_ui_fixture",
    employee_id: employeeId,
    employee: {
      id: employeeId,
      name: "Sage",
      status: "live fixture",
      profile_id: "contractor_estimator",
      web_route: `/agent/${employeeId}`,
      created_at: "2026-07-09T09:00:00Z",
    },
    runtime_health: {
      status: "healthy",
      checked_at: now,
      backend_type: "ui_fixture",
      api_ok: true,
      sms_number_present: true,
      message: "UI fixture mode is using representative local data only.",
    },
    artifacts: [
      {
        id: "art_estimate_jane",
        kind: "estimate",
        mime_type: "text/html",
        storage_ref: null,
        payload: {
          customer_name: "Jane Miller",
          job_description: "Kitchen repaint, cabinets excluded, two coats on walls and trim.",
          recommended_total: 420000,
        },
        created_at: "2026-07-09T10:45:00Z",
      },
      {
        id: "art_before_after",
        kind: "media_asset",
        mime_type: "image/png",
        storage_ref: null,
        payload: {
          customer_name: "Ridgeview HOA",
          job_description: "Before/after gallery concept for a review request.",
        },
        created_at: "2026-07-09T10:20:00Z",
      },
      {
        id: "art_weekly_report",
        kind: "dataset_report",
        mime_type: "text/html",
        storage_ref: null,
        payload: {
          customer_name: "Owner brief",
          job_description: "Three open estimates, two waiting follow-ups, one payment reminder.",
        },
        created_at: "2026-07-09T09:55:00Z",
      },
    ],
    approvals: [
      {
        id: "appr_send_jane",
        action_key: "send_estimate_email",
        summary: "Send Jane Miller the kitchen repaint estimate for $4,200 with the PDF preview attached.",
        risk_level: "customer-facing",
        refs: { artifact_id: "art_estimate_jane", customer_email: "jane@example.com" },
        expires_at: "2026-07-10T11:30:00Z",
      },
      {
        id: "appr_deposit",
        action_key: "send_deposit_invoice",
        summary: "Send a $1,260 deposit invoice for the Ridgeview HOA exterior touch-up.",
        risk_level: "money",
        refs: { invoice_id: "inv_deposit_1" },
        expires_at: "2026-07-10T11:30:00Z",
      },
    ],
    messages: [
      {
        id: "msg_1",
        direction: "from_owner",
        body: "Can you price Jane's kitchen repaint and prep the email?",
        status: "delivered",
        created_at: "2026-07-09T10:35:00Z",
      },
      {
        id: "msg_2",
        direction: "to_owner",
        body: "I drafted the estimate and staged the customer email. It is waiting for your approval before anything leaves the business.",
        status: "delivered",
        provider_id: "fixture_reply_1",
        created_at: "2026-07-09T10:45:00Z",
      },
    ],
    connectors: [
      {
        id: "conn_gmail",
        connector_key: "gmail",
        provider: "gmail",
        status: "connected",
        external_email: "owner@example.com",
      },
      {
        id: "conn_stripe",
        connector_key: "stripe",
        provider: "stripe",
        status: "needs_reauth",
        last_error: "Reconnect payments before sending new live invoices.",
      },
      {
        id: "conn_drive",
        connector_key: "drive",
        provider: "google_drive",
        status: "not_connected",
        last_error: "Connect files to use prior proposals and job photos.",
      },
    ],
    stripe_invoices: [
      {
        id: "inv_deposit_1",
        estimate_id: "art_estimate_jane",
        stripe_invoice_id: "in_fixture_123",
        deposit_amount: 126000,
        hosted_invoice_url: "https://example.com/fixture-invoice",
        status: "draft",
      },
    ],
    reminders: [
      {
        id: "rem_followup_jane",
        job_id: "job_jane",
        scheduled_at: "2026-07-10T14:00:00Z",
        channel: "sms",
        status: "scheduled",
        message: "Follow up with Jane if she has not approved the estimate.",
      },
    ],
    job_commitments: [
      {
        id: "job_jane",
        estimate_id: "art_estimate_jane",
        customer_ref: "Jane Miller",
        start_at: "2026-07-16T13:00:00Z",
        start_window: "next Wednesday afternoon",
        notes: "Kitchen repaint, customer may add trim after review.",
        source_ref: "fixture",
        created_at: "2026-07-09T10:50:00Z",
      },
    ],
    work_events: [
      workEvent(
        "we_send_jane",
        "review",
        "Estimate ready for Jane",
        "Kitchen repaint estimate is ready at $4,200. I will not send it until you approve.",
        {
          type: "outbound_message",
          title: "Estimate email to Jane",
          refs: { to: "jane@example.com", artifact_id: "art_estimate_jane", approval_id: "appr_send_jane" },
          leaves_business: true,
          reversible: false,
          acceptance: ["approve", "edit", "reject"],
        },
        "Review the email and estimate.",
      ),
      workEvent(
        "we_deposit",
        "review",
        "Deposit invoice drafted",
        "A $1,260 deposit invoice is ready for Ridgeview HOA.",
        {
          type: "money_movement",
          title: "Deposit invoice",
          refs: { hosted_invoice_url: "https://example.com/fixture-invoice", approval_id: "appr_deposit" },
          money: { involved: true, amount_cents: 126000, currency: "usd" },
          leaves_business: true,
          reversible: false,
          acceptance: ["approve", "reject"],
        },
      ),
      workEvent(
        "we_report",
        "notify",
        "Weekly pipeline brief",
        "Three open estimates are waiting: Jane, Ridgeview HOA, and Maple Street trim.",
        {
          type: "dataset_report",
          title: "Pipeline report",
          refs: { artifact_id: "art_weekly_report" },
          acceptance: ["acknowledge"],
          view: {
            kind: "table",
            columns: ["Customer", "Work", "Status"],
            rows: [
              ["Jane Miller", "Kitchen repaint", "needs approval"],
              ["Ridgeview HOA", "Exterior touch-up", "deposit draft"],
              ["Maple Street", "Trim repair", "needs photos"],
            ],
          },
        },
      ),
      workEvent(
        "we_media",
        "question",
        "Review post idea",
        "I can turn the Ridgeview before/after gallery into a short review request after the job closes.",
        {
          type: "media_asset",
          title: "Before/after gallery concept",
          refs: { artifact_id: "art_before_after" },
          acceptance: ["respond", "acknowledge"],
        },
        "Reply with the tone you want for the post.",
      ),
      workEvent(
        "we_connector",
        "question",
        "Payments need reconnecting",
        "Stripe needs attention before I can create new live payment links.",
        {
          type: "external_system_action",
          title: "Reconnect payments",
          refs: { connector_id: "conn_stripe" },
          acceptance: ["respond", "acknowledge"],
        },
        "Open Connected to repair it.",
      ),
    ],
    abilities: [
      {
        id: "ability_estimates",
        label: "Create estimates and documents",
        category: "documents",
        status: "ready",
        summary: "Draft structured estimates, save outputs, and prepare owner-safe previews.",
        source: "manager",
      },
      {
        id: "ability_email",
        label: "Draft and send email",
        category: "communication",
        status: "ready",
        summary: "Email is connected; customer sends still wait for your approval.",
        source: "connector",
      },
      {
        id: "ability_payments",
        label: "Collect deposits",
        category: "money",
        status: "needs_connection",
        summary: "Reconnect payments before sending live deposit invoices.",
        source: "connector",
      },
      {
        id: "ability_media",
        label: "Prepare media previews",
        category: "office",
        status: "policy_gated",
        summary: "Images, video, and social drafts can be previewed here before publishing.",
        source: "policy",
      },
    ],
    connection_surfaces: [
      {
        id: "connection:email",
        label: "Email",
        category: "communication",
        state: "working",
        account_label: "owner@example.com",
        health: "Ready",
        last_event: "Customer reply at 2026-07-09T10:45:00Z",
        last_action: "Connection tested at 2026-07-09T10:30:00Z",
        what_employee_can_do: "Draft customer emails; Send customer email; Watch for customer replies",
        setup_requirement: null,
        connector_id: "conn_gmail",
        capability_keys: ["manager_tool:create_email_draft", "manager_tool:send_email_draft"],
        proof: { source_table: "connector_accounts", source_id: "conn_gmail", inbound_event_id: "we_send_jane" },
      },
      {
        id: "connection:payments",
        label: "Payments",
        category: "money",
        state: "needs_you",
        account_label: null,
        health: "Reconnect payments before sending new live invoices.",
        last_event: "Deposit invoice drafted at 2026-07-09T10:40:00Z",
        last_action: null,
        what_employee_can_do: "Prepare deposit invoices, track payment status, and surface payment follow-ups.",
        setup_requirement: null,
        connector_id: "conn_stripe",
        capability_keys: ["manager_tool:create_deposit_invoice", "manager_tool:send_deposit_invoice"],
        proof: { source_table: "connector_accounts", source_id: "conn_stripe", inbound_event_id: "we_deposit" },
      },
      {
        id: "connection:accounting",
        label: "Accounting",
        category: "accounting",
        state: "not_connected",
        account_label: null,
        health: "Connect the accounting system.",
        last_event: null,
        last_action: null,
        what_employee_can_do: "Prepare approved accounting entries, look up records, and summarize key reports.",
        setup_requirement: "Connect the accounting system.",
        connector_id: null,
        capability_keys: ["manager_tool:connect_quickbooks", "manager_tool:create_expense"],
        proof: { source_table: "capability_registry", source_id: "accounting" },
      },
      {
        id: "connection:files",
        label: "Files",
        category: "documents",
        state: "not_connected",
        account_label: null,
        health: "Connect files to use prior proposals and job photos.",
        last_event: null,
        last_action: null,
        what_employee_can_do: "Use job documents, photos, blueprints, and stored outputs when a file system is connected.",
        setup_requirement: "Connect file storage when document context is needed.",
        connector_id: "conn_drive",
        capability_keys: [],
        proof: { source_table: "connector_accounts", source_id: "conn_drive" },
      },
    ],
    outputs: [
      {
        id: "artifact:art_estimate_jane",
        type: "artifact",
        title: "Estimate for Jane Miller",
        status: "ready",
        created_at: "2026-07-09T10:45:00Z",
        href: `/agent/${employeeId}/output/art_estimate_jane`,
        artifact_id: "art_estimate_jane",
        summary: "Kitchen repaint, two coats, walls and trim.",
      },
      {
        id: "invoice:inv_deposit_1",
        type: "invoice",
        title: "Deposit invoice $1,260.00",
        status: "draft",
        href: "https://example.com/fixture-invoice",
        summary: "Draft Stripe deposit invoice; approval-gated.",
      },
      {
        id: "artifact:art_before_after",
        type: "generic",
        title: "Before/after gallery concept",
        status: "draft",
        created_at: "2026-07-09T10:20:00Z",
        href: `/agent/${employeeId}/output/art_before_after`,
        artifact_id: "art_before_after",
        summary: "Representative media artifact for image/video preview design.",
      },
      {
        id: "artifact:art_weekly_report",
        type: "generic",
        title: "Weekly pipeline report",
        status: "ready",
        created_at: "2026-07-09T09:55:00Z",
        href: `/agent/${employeeId}/output/art_weekly_report`,
        artifact_id: "art_weekly_report",
        summary: "Representative dataset/report output for UI-only testing.",
      },
    ],
    tasks: [
      {
        id: "approval:appr_send_jane",
        type: "approval",
        title: "Approve Jane estimate send",
        status: "needs_you",
        summary: "Customer-facing email is staged and waiting.",
        created_at: "2026-07-09T10:45:00Z",
        target_id: "appr_send_jane",
      },
      {
        id: "approval:appr_deposit",
        type: "approval",
        title: "Approve deposit invoice",
        status: "needs_you",
        summary: "Money movement stays gated until you approve.",
        created_at: "2026-07-09T10:40:00Z",
        target_id: "appr_deposit",
      },
      {
        id: "connector:conn_stripe",
        type: "connector",
        title: "Payments need attention",
        status: "blocked",
        summary: "Reconnect Stripe before sending live payment links.",
        target_id: "conn_stripe",
      },
      {
        id: "reminder:rem_followup_jane",
        type: "reminder",
        title: "Follow up with Jane",
        status: "scheduled",
        summary: "Scheduled for tomorrow afternoon.",
        created_at: "2026-07-10T14:00:00Z",
        target_id: "rem_followup_jane",
      },
    ],
    resurface_items: [
      {
        id: "resurface:approval:appr_send_jane",
        kind: "review",
        title: "Approve Jane estimate send",
        why: "Customer-facing email is staged and waiting.",
        status: "needs_you",
        resurface_at: "2026-07-09T10:45:00Z",
        channel: "both",
        source_envelope_id: null,
        target: { kind: "approval", id: "appr_send_jane" },
        proof: { source_table: "approvals", source_id: "appr_send_jane", approval_id: "appr_send_jane" },
      },
      {
        id: "resurface:connector:conn_stripe",
        kind: "connector",
        title: "Payments need attention",
        why: "Reconnect Stripe before sending live payment links.",
        status: "blocked",
        resurface_at: null,
        channel: "web",
        source_envelope_id: null,
        target: { kind: "connection", id: "connection:payments" },
        proof: { source_table: "connector_accounts", source_id: "conn_stripe" },
      },
      {
        id: "resurface:reminder:rem_followup_jane",
        kind: "reminder",
        title: "Follow up with Jane",
        why: "Scheduled for tomorrow afternoon.",
        status: "scheduled",
        resurface_at: "2026-07-10T14:00:00Z",
        channel: "both",
        source_envelope_id: null,
        target: { kind: "task", id: "reminder:rem_followup_jane" },
        proof: { source_table: "reminders", source_id: "rem_followup_jane" },
      },
    ],
  };
  return JSON.parse(JSON.stringify(payload)) as ResourcePayload;
}
