/* GENERATED by scripts/ui-variant.mjs. Do not edit by hand. */
import { lazy } from "react";
import type { UiVariantManifest } from "@amtech/shared";
import referenceClientManifest from "../../../ui-variants/reference-client/variant.json";
import radicalCanvasManifest from "../../../ui-variants/radical-canvas/variant.json";
import editorialStudioManifest from "../../../ui-variants/editorial-studio/variant.json";

export const UI_VARIANT_REGISTRY = {
  "reference-client": { manifest: referenceClientManifest as UiVariantManifest, Component: lazy(() => import("../../../ui-variants/reference-client/index")) },
  "radical-canvas": { manifest: radicalCanvasManifest as UiVariantManifest, Component: lazy(() => import("../../../ui-variants/radical-canvas/index")) },
  "editorial-studio": { manifest: editorialStudioManifest as UiVariantManifest, Component: lazy(() => import("../../../ui-variants/editorial-studio/index")) },
} as const;

export type UiVariantRegistryId = keyof typeof UI_VARIANT_REGISTRY;
export const UI_VARIANT_IDS = Object.keys(UI_VARIANT_REGISTRY) as UiVariantRegistryId[];
export function isUiVariantRegistryId(value: string): value is UiVariantRegistryId { return value in UI_VARIANT_REGISTRY; }
