/* GENERATED by scripts/ui-variant.mjs. Do not edit by hand. */
import { lazy } from "react";
import type { UiVariantManifest } from "@amtech/shared";
import manifest0 from "../../../ui-variants/editorial-studio/variant.json";
import manifest1 from "../../../ui-variants/radical-canvas/variant.json";
import manifest2 from "../../../ui-variants/reference-client/variant.json";

export const UI_VARIANT_REGISTRY = {
  "editorial-studio": { manifest: manifest0 as UiVariantManifest, Component: lazy(() => import("../../../ui-variants/editorial-studio/index")) },
  "radical-canvas": { manifest: manifest1 as UiVariantManifest, Component: lazy(() => import("../../../ui-variants/radical-canvas/index")) },
  "reference-client": { manifest: manifest2 as UiVariantManifest, Component: lazy(() => import("../../../ui-variants/reference-client/index")) },
} as const;

export type UiVariantRegistryId = keyof typeof UI_VARIANT_REGISTRY;
export const UI_VARIANT_IDS = Object.keys(UI_VARIANT_REGISTRY) as UiVariantRegistryId[];
export function isUiVariantRegistryId(value: string): value is UiVariantRegistryId { return value in UI_VARIANT_REGISTRY; }
