/**
 * GENERATED by scripts/ui-lab-registry.mjs.
 * Do not edit by hand. The canonical inputs are ui-lab/presets/** and
 * ui-lab/assignments.json.
 */
export const APPROVED_UI_PRESET_ASSIGNMENTS = [] as const;

export const UI_LAB_RUNTIME_REGISTRY_DIGEST = "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945";
