/**
 * GENERATED by scripts/ui-lab-registry.mjs.
 * Do not edit by hand. The canonical inputs are ui-lab/presets/** and
 * ui-lab/assignments.json.
 */
export const APPROVED_UI_PRESET_ASSIGNMENTS = [] as const;

export const UI_LAB_RUNTIME_REGISTRY_DIGEST = "empty";
